// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUVlbId0GE4SaRJDrzkePYaYxtPZzL0Wk',
    appId: '1:211538429941:web:fd7b2b4656616b2e4bc2bc',
    messagingSenderId: '211538429941',
    projectId: 'chatapp-f4c4b',
    authDomain: 'chatapp-f4c4b.firebaseapp.com',
    storageBucket: 'chatapp-f4c4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtuwmkhUKWT9QHtiC3g_7w_qBZipRIsls',
    appId: '1:211538429941:android:982b024a99fa3be74bc2bc',
    messagingSenderId: '211538429941',
    projectId: 'chatapp-f4c4b',
    storageBucket: 'chatapp-f4c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRCGqA_kSt5Hcmb9GVMS7zBbvR22xT3WQ',
    appId: '1:211538429941:ios:8581733ca209b4544bc2bc',
    messagingSenderId: '211538429941',
    projectId: 'chatapp-f4c4b',
    storageBucket: 'chatapp-f4c4b.firebasestorage.app',
    iosBundleId: 'com.example.flutterTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRCGqA_kSt5Hcmb9GVMS7zBbvR22xT3WQ',
    appId: '1:211538429941:ios:8581733ca209b4544bc2bc',
    messagingSenderId: '211538429941',
    projectId: 'chatapp-f4c4b',
    storageBucket: 'chatapp-f4c4b.firebasestorage.app',
    iosBundleId: 'com.example.flutterTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUVlbId0GE4SaRJDrzkePYaYxtPZzL0Wk',
    appId: '1:211538429941:web:3d2acf25c696d3494bc2bc',
    messagingSenderId: '211538429941',
    projectId: 'chatapp-f4c4b',
    authDomain: 'chatapp-f4c4b.firebaseapp.com',
    storageBucket: 'chatapp-f4c4b.firebasestorage.app',
  );
}
