// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAARiU6TIZUNJ3TOwLOvAcoIcoDsy-pChA',
    appId: '1:546616686280:web:0a20917c2be2c5fa5f17fd',
    messagingSenderId: '546616686280',
    projectId: 'aututorial-19015',
    authDomain: 'aututorial-19015.firebaseapp.com',
    storageBucket: 'aututorial-19015.firebasestorage.app',
    measurementId: 'G-V6VW8K1QDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5OMC1vQRVDMKua0aHKHBlUV8EddALTd4',
    appId: '1:546616686280:android:7b696b10400513765f17fd',
    messagingSenderId: '546616686280',
    projectId: 'aututorial-19015',
    storageBucket: 'aututorial-19015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3hrL7IIXO1-gPNm8Srfy9GK_7nVbcW4Q',
    appId: '1:546616686280:ios:83cd546d6dc864c85f17fd',
    messagingSenderId: '546616686280',
    projectId: 'aututorial-19015',
    storageBucket: 'aututorial-19015.firebasestorage.app',
    iosBundleId: 'com.example.flutterTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3hrL7IIXO1-gPNm8Srfy9GK_7nVbcW4Q',
    appId: '1:546616686280:ios:83cd546d6dc864c85f17fd',
    messagingSenderId: '546616686280',
    projectId: 'aututorial-19015',
    storageBucket: 'aututorial-19015.firebasestorage.app',
    iosBundleId: 'com.example.flutterTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAARiU6TIZUNJ3TOwLOvAcoIcoDsy-pChA',
    appId: '1:546616686280:web:346b1e1d11b18eef5f17fd',
    messagingSenderId: '546616686280',
    projectId: 'aututorial-19015',
    authDomain: 'aututorial-19015.firebaseapp.com',
    storageBucket: 'aututorial-19015.firebasestorage.app',
    measurementId: 'G-PJCR82WDTS',
  );
}
